### ISSUE TITLE
Failed to install module on Windows

### ISSUE THREAD

**Issue by daniluk4000** [antixrist/node-phpmorphy#12]
При установке ловлю следующую ошибку:

> phpmorphy@2.3.1 clean C:\Users\danil\WebstormProjects\foo\node_modules\phpmorphy
> rm -rf dist && mkdir dist

"rm" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

**Comment by antixrist** [comment]
Не используйте виндовую командную строку.
Поставьте [Git for Windows](https://git-scm.com/download/win) и юзайте Git Bash.
