### ISSUE TITLE
ERROR 'ет'

### ISSUE THREAD

**Issue by zirill** [antixrist/node-phpmorphy#2]
const Morphy = require('phpmorphy').default;
const morphy = new Morphy('ru', {
//  nojo:                false,
    storage:             Morphy.STORAGE_MEM,
    predict_by_suffix:   true,
    predict_by_db:       true,
    graminfo_as_text:    true,
    use_ancodes_cache:   false,
    resolve_ancodes:     Morphy.RESOLVE_ANCODES_AS_TEXT
});

morphy.lemmatize('ет'); // -- ERROR if text = 'ет'

**Comment by antixrist** [comment]
fixed in https://github.com/antixrist/node-phpmorphy/commit/6868dfae4eb976197e99f6ac23402bd976509d45
