### ISSUE TITLE
Add info about installation nuances to windows (missing rm)

### ISSUE THREAD

**Issue by FVGame** [antixrist/node-phpmorphy#23]
> Не используйте виндовую командную строку.
> Поставьте [Git for Windows](https://git-scm.com/download/win) и юзайте Git Bash.

_Originally posted by @antixrist in https://github.com/antixrist/node-phpmorphy/issues/12#issuecomment-596923034_

Пожалуйста, добавьте эту информацию с решением проблемы при установке на windows связанную с отсутствием "rm".

Ещё пара возможных решений этой проблемы: 

1. Если надо/хочется использовать другой терминал, но установлен (установите) "Git for windows" - добавьте в системные переменные (в Path) путь до подпапки ./usr/bin находящейся в папке, где установлен git (пример пути: C:\Program Files\Git\usr\bin).
2. Установить более старую версию phpMorphy ещё не использующую rm, например 2.1.2 (это последняя версия без rm)

**Comment by AlexeyAndKartashov** [comment]
Готово, спасибо!
