### ISSUE TITLE
phpjs has a dependency with critical security vulnerabilities, any plans to shift to locutus?

### ISSUE THREAD

**Issue by deemeetree** [antixrist/node-phpmorphy#4]

**Comment by antixrist** [comment]
Hi!

Thanks for reference to `locutus` - it's very cool project. I did not know about its existence.

Yes, I have plans for the next couple of months to rewrite this projects for more maintainable and readable code with tests, eslint, prettier etc. Stay tuned :)

**Comment by deemeetree** [comment]
Окей, я просто не мог ждать, поэтому проапдейтил всё сам )

**Comment by antixrist** [comment]
@deemeetree Понял) у меня просто в планах немного больше изменений - выпилить вебпак, провести ревизию зависимостей, возможно переписать на ts. Если вас пока ваша версия устраивает, то супер)
Как будут готовые обновления, я вам здесь маякну

**Comment by deemeetree** [comment]
@antixrist ну смотрите, просто в данной своей инкарнации библиотека подгружает dependencies с criticial vulnerabilities, а те изменения, которые внёс я, они не breaking, я там в pull request всё написал. просто сделал, чтобы подгружался `locutus` вместо `phpjs` и поменял во всем коде ссылки (в locutus функции вызываются `strings.strpos` вместо просто `strpos` — то есть, очень всё тривиально. а людям может помочь. другие зависимости там ок, ни одного предупреждения.

а, кстати, почему хотите выпилить webpack?

**Comment by antixrist** [comment]
@deemeetree С `locutus` вопросов нет, спасибо вам) Сегодня вмёржу вашу реквест, поправлю `package.json` и опубликую обновлённую версию.

> а, кстати, почему хотите выпилить webpack?

Вебпак для билда слишком оверхед. Плюс здесь вторая версия, давно устаревшая, а в нюансах последнего вебпака разбираться прямо сейчас мне не очень продуктивно.
Для сборки можно обойтись чистым бабелем, но для этого его надо обновить и настроить до актуальной версии.
Ну и надо привести код в порядок (eslint, prettier), написать тесты, тайпинги и вот это вот всё)

**Comment by antixrist** [comment]
@deemeetree обновил пакет на npm с вашим pr, можете обновляться

**Comment by deemeetree** [comment]
супер, спасибо @antixrist

**Comment by antixrist** [comment]
@deemeetree не за что)
